#
services:
  telegram-forwarder2:
    image: angelbean/telegramforwarder2:latest
    container_name: telegram-forwarder2
    stdin_open: true
    tty: true
    # RSS网页端口, RSS相关设置在.env中
    ports:
      - 9000:8000
    volumes:
      - ./db:/app/db
      - ./.env:/app/.env
      - ./logs:/app/logs
      - ./sessions:/app/sessions
      - ./temp:/app/temp
      - ./ufb/config:/app/ufb/config
      - ./config:/app/config
      - ./rss/data:/app/rss/data
      - ./rss/media:/app/rss/media

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256m
          pids: 100
    memswap_limit: 512m

    restart: unless-stopped

